/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controlingresos;

/**
 *
 * @author usuario
 */
public class Mensaje extends javax.swing.JFrame {
    AbstactFactory metodo = new AbstactFactory();

    public String mensaje;

    /**
     * Creates new form Mensaje
     */
    public Mensaje(String mensaje) {
        this.mensaje = mensaje;
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void getBack(){
        if(mensaje.equals("VistaCancelarMovimiento")){
            System.out.println("regresando a VistaCancelarMovimiento");
            VistaCancelarMovimiento crearMov = metodo.getVistaCanMov();
            crearMov.setVisible(true);
            this.setVisible(false);
            
            
        }else if(mensaje.equals("VistaIntroducirMovimiento")){
            System.out.println("regresando a VistaIntroducirMovimiento");
             VistaIntroducirMovimiento crearMov = metodo.getVistaIntroMov();
            crearMov.setVisible(false);
            this.setVisible(false);
            
        }else if(mensaje.equals("VistaConsultaIntervalo")){
             VistaConsultaIntervalo crearMov = metodo.getVistaConInt();
            crearMov.setVisible(true);
            this.setVisible(false);
            
        }else if(mensaje.equals("VistaSaludFinanciera")){
            System.out.println("regresando a VistaSaludFinanciera");
            VistaSaludFinanciera crearMov =  metodo.getVistaSalud();
            crearMov.setVisible(true);
            this.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("La accion a sido completada correctamente");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jButton1)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addComponent(jButton1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        getBack();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
