/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controlingresos;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author usuario
 */
public class Principal extends javax.swing.JFrame {
    AbstactFactory metodo = new AbstactFactory();
    VistaSaludFinanciera metodoSalud = new VistaSaludFinanciera();
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        ConexionDB conexiondb = ConexionDB.getInstance();
        
        
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnCrearMovimiento = new javax.swing.JButton();
        btnCancelarMovimiento = new javax.swing.JButton();
        btnConsultaIntervalo = new javax.swing.JButton();
        btnSaludFinanciera = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cerrarApp = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearMovimiento.setText("Crear Movimiento");
        btnCrearMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMovimientoActionPerformed(evt);
            }
        });

        btnCancelarMovimiento.setText("Cancelar Movimiento");
        btnCancelarMovimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMovimientoActionPerformed(evt);
            }
        });

        btnConsultaIntervalo.setText("Consultar Balance por intervalo de tiempo");
        btnConsultaIntervalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaIntervaloActionPerformed(evt);
            }
        });

        btnSaludFinanciera.setText("Consultar salud financiera");
        btnSaludFinanciera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaludFinancieraActionPerformed(evt);
            }
        });

        jLabel1.setText("Control de Ingresos/Egresos");

        cerrarApp.setText("Cerrar aplicacion");
        cerrarApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarAppActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrearMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnCancelarMovimiento)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnConsultaIntervalo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnSaludFinanciera))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(cerrarApp)))
                .addGap(46, 161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(btnCrearMovimiento)
                .addGap(50, 50, 50)
                .addComponent(btnCancelarMovimiento)
                .addGap(52, 52, 52)
                .addComponent(btnConsultaIntervalo)
                .addGap(64, 64, 64)
                .addComponent(btnSaludFinanciera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(cerrarApp)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMovimientoActionPerformed
        // TODO add your handling code here:
        
        VistaIntroducirMovimiento crearMov = metodo.getVistaIntroMov();
        
        crearMov.setVisible(true);
        this.setVisible(false);
        
        
        
    }//GEN-LAST:event_btnCrearMovimientoActionPerformed

    private void btnCancelarMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMovimientoActionPerformed
        // TODO add your handling code here:
        VistaCancelarMovimiento crearMov = metodo.getVistaCanMov();
        crearMov.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarMovimientoActionPerformed

    private void btnConsultaIntervaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaIntervaloActionPerformed
        // TODO add your handling code here:
        VistaConsultaIntervalo crearMov = metodo.getVistaConInt();
        crearMov.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultaIntervaloActionPerformed

    private void btnSaludFinancieraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaludFinancieraActionPerformed
        // TODO add your handling code here:
        VistaSaludFinanciera crearMov =  metodo.getVistaSalud();
        crearMov.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSaludFinancieraActionPerformed

    private void cerrarAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarAppActionPerformed
        // TODO add your handling code here:
        System.exit(0);
       
    }//GEN-LAST:event_cerrarAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarMovimiento;
    private javax.swing.JButton btnConsultaIntervalo;
    private javax.swing.JButton btnCrearMovimiento;
    private javax.swing.JButton btnSaludFinanciera;
    private javax.swing.JButton cerrarApp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
